name: Assign PR to User

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR
        uses: actions-ecosystem/action-assign@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assigness: 'Preales'
