name: Assign PR to User

on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR
        uses: kentaro-m/auto-assign-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assigness: 'Preales'
