name: tbls

on: 
  push:
    branches: [feature/test_linea_base]

jobs:
  doc:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
      - name: Checkout .tbls.yml
        uses: actions/checkout@v4        
        
      - name: Debug environment variables
        run: |
          echo "DB_USER: $DB_USER"
          echo "PASS_DB: $PASS_DB"
          echo "DB_HOST: $DB_HOST"
        env:
          DB_USER: ${{ secrets.DB_USER }}
          PASS_DB: ${{ secrets.PASS_DB }}
          DB_HOST: ${{ secrets.DB_HOST }}
        
      - name: Update DB_USER in YAML file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'tbls.yml'
          propertyPath: 'dsn'
          value: "sqlserver://${{ secrets.DB_USER }}:${{ secrets.PASS_DB }}@${{ secrets.DB_HOST }}:1433/postobon-neg-db"
          commitChange: false

      - name: Print YAML file
        run: cat tbls.yml
        
      - name: Setup tbls v1
        uses: k1low/setup-tbls@v1

      - name: Run tbls for generate database document
        run: tbls doc
        
