name: tbls

on: 
  push:
    branches: [feature/test_linea_base]

jobs:
  doc:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
      - name: Checkout .tbls.yml
        uses: actions/checkout@v4
        
      - name: Update DB_USER in YAML file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'tbls.yml'
          propertyPath: 'dsn1'
          value: ${{ vars.DNS }}
          commitChange: false

      - name: Update DB_USER in YAML file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'tbls.yml'
          propertyPath: 'user'
          value: ${{ vars.USER_DB }}
      
      - name: Update DB_USER in YAML file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'tbls.yml'
          propertyPath: 'code'
          value: ${{ vars.CODE_DB }}

      - name: Update DB_USER in YAML file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'tbls.yml'
          propertyPath: 'host'
          value: ${{ vars.HOST_DB }}

      - name: Print YAML file
        run: cat tbls.yml

      - name: Print value
        run: echo '${{ vars.USER_DB }}:${{ vars.CODE_DB }}:${{ vars.HOST_DB }}:1433/postobon-neg-db'
        
      - name: Print DNS
        run: echo ${{ vars.DNS }}

      - name: Setup tbls v1
        uses: k1low/setup-tbls@v1

      - name: Run tbls for generate database document
        run: tbls doc
        
